//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayoutingTester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LayoutingTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;area&quot;:{&quot;432.5&quot;:{&quot;762.5&quot;:&quot;can-build&quot;,&quot;763.5&quot;:&quot;can-build&quot;,&quot;764.5&quot;:&quot;can-build&quot;,&quot;765.5&quot;:&quot;can-build&quot;,&quot;766.5&quot;:&quot;can-build&quot;,&quot;767.5&quot;:&quot;can-build&quot;,&quot;768.5&quot;:&quot;can-build&quot;,&quot;769.5&quot;:&quot;can-build&quot;,&quot;770.5&quot;:&quot;can-build&quot;,&quot;771.5&quot;:&quot;can-build&quot;,&quot;772.5&quot;:&quot;can-build&quot;,&quot;773.5&quot;:&quot;can-build&quot;,&quot;774.5&quot;:&quot;can-build&quot;,&quot;775.5&quot;:&quot;can-build&quot;,&quot;776.5&quot;:&quot;can-build&quot;,&quot;777.5&quot;:&quot;can-build&quot;,&quot;778.5&quot;:&quot;can-build&quot;,&quot;779.5&quot;:&quot;can-build&quot;,&quot;780.5&quot;:&quot;can-build&quot;,&quot;781.5&quot;:&quot;can-build&quot;,&quot;782.5&quot;:&quot;can-build&quot;,&quot;783.5&quot;:&quot;can-build&quot;,&quot;784.5&quot;:&quot;can-build&quot;,&quot;785.5&quot;:&quot;can-build&quot;,&quot;786.5&quot;:&quot....
        /// </summary>
        internal static string Oilfield1 {
            get {
                return ResourceManager.GetString("Oilfield1", resourceCulture);
            }
        }
    }
}
