//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayoutingTester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LayoutingTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;area&quot;:{&quot;432.5&quot;:{&quot;762.5&quot;:&quot;can-build&quot;,&quot;763.5&quot;:&quot;can-build&quot;,&quot;764.5&quot;:&quot;can-build&quot;,&quot;765.5&quot;:&quot;can-build&quot;,&quot;766.5&quot;:&quot;can-build&quot;,&quot;767.5&quot;:&quot;can-build&quot;,&quot;768.5&quot;:&quot;can-build&quot;,&quot;769.5&quot;:&quot;can-build&quot;,&quot;770.5&quot;:&quot;can-build&quot;,&quot;771.5&quot;:&quot;can-build&quot;,&quot;772.5&quot;:&quot;can-build&quot;,&quot;773.5&quot;:&quot;can-build&quot;,&quot;774.5&quot;:&quot;can-build&quot;,&quot;775.5&quot;:&quot;can-build&quot;,&quot;776.5&quot;:&quot;can-build&quot;,&quot;777.5&quot;:&quot;can-build&quot;,&quot;778.5&quot;:&quot;can-build&quot;,&quot;779.5&quot;:&quot;can-build&quot;,&quot;780.5&quot;:&quot;can-build&quot;,&quot;781.5&quot;:&quot;can-build&quot;,&quot;782.5&quot;:&quot;can-build&quot;,&quot;783.5&quot;:&quot;can-build&quot;,&quot;784.5&quot;:&quot;can-build&quot;,&quot;785.5&quot;:&quot;can-build&quot;,&quot;786.5&quot;:&quot....
        /// </summary>
        internal static string Oilfield1 {
            get {
                return ResourceManager.GetString("Oilfield1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;area&quot;:{&quot;-5466.5&quot;:{&quot;-1094.5&quot;:&quot;can-build&quot;,&quot;-1093.5&quot;:&quot;can-build&quot;,&quot;-1092.5&quot;:&quot;can-build&quot;,&quot;-1091.5&quot;:&quot;can-build&quot;,&quot;-1090.5&quot;:&quot;can-build&quot;,&quot;-1089.5&quot;:&quot;can-build&quot;,&quot;-1088.5&quot;:&quot;can-build&quot;,&quot;-1087.5&quot;:&quot;can-build&quot;,&quot;-1086.5&quot;:&quot;can-build&quot;,&quot;-1085.5&quot;:&quot;can-build&quot;,&quot;-1084.5&quot;:&quot;can-build&quot;,&quot;-1083.5&quot;:&quot;can-build&quot;,&quot;-1082.5&quot;:&quot;can-build&quot;,&quot;-1081.5&quot;:&quot;can-build&quot;,&quot;-1080.5&quot;:&quot;can-build&quot;,&quot;-1079.5&quot;:&quot;can-build&quot;,&quot;-1078.5&quot;:&quot;can-build&quot;,&quot;-1077.5&quot;:&quot;can-build&quot;,&quot;-1076.5&quot;:&quot;can-build&quot;,&quot;-1075.5&quot;:&quot;can-build&quot;,&quot;-1074.5&quot;:&quot;can-build&quot;,&quot;-1073.5&quot;:&quot;can-build&quot;,&quot;-1072.5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Oilfield2 {
            get {
                return ResourceManager.GetString("Oilfield2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;area&quot;:{&quot;-6010.5&quot;:{&quot;-138.5&quot;:&quot;can-build&quot;,&quot;-137.5&quot;:&quot;can-build&quot;,&quot;-136.5&quot;:&quot;can-build&quot;,&quot;-135.5&quot;:&quot;can-build&quot;,&quot;-134.5&quot;:&quot;can-build&quot;,&quot;-133.5&quot;:&quot;can-build&quot;,&quot;-132.5&quot;:&quot;can-build&quot;,&quot;-131.5&quot;:&quot;can-build&quot;,&quot;-130.5&quot;:&quot;can-build&quot;,&quot;-129.5&quot;:&quot;can-build&quot;,&quot;-128.5&quot;:&quot;can-build&quot;,&quot;-127.5&quot;:&quot;can-build&quot;,&quot;-126.5&quot;:&quot;can-build&quot;,&quot;-125.5&quot;:&quot;can-build&quot;,&quot;-124.5&quot;:&quot;can-build&quot;,&quot;-123.5&quot;:&quot;can-build&quot;,&quot;-122.5&quot;:&quot;can-build&quot;,&quot;-121.5&quot;:&quot;can-build&quot;,&quot;-120.5&quot;:&quot;can-build&quot;,&quot;-119.5&quot;:&quot;can-build&quot;,&quot;-118.5&quot;:&quot;can-build&quot;,&quot;-117.5&quot;:&quot;can-build&quot;,&quot;-116.5&quot;:&quot;can-build&quot;,&quot;-115.5&quot;: [rest of string wa....
        /// </summary>
        internal static string Oilfield3 {
            get {
                return ResourceManager.GetString("Oilfield3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;area&quot;:{&quot;-6499.5&quot;:{&quot;-914.5&quot;:&quot;can-build&quot;,&quot;-913.5&quot;:&quot;can-build&quot;,&quot;-912.5&quot;:&quot;can-build&quot;,&quot;-911.5&quot;:&quot;can-build&quot;,&quot;-910.5&quot;:&quot;reserved-for-pump&quot;,&quot;-909.5&quot;:&quot;reserved-for-pump&quot;,&quot;-908.5&quot;:&quot;reserved-for-pump&quot;,&quot;-907.5&quot;:&quot;can-build&quot;,&quot;-906.5&quot;:&quot;can-build&quot;,&quot;-905.5&quot;:&quot;can-build&quot;,&quot;-904.5&quot;:&quot;can-build&quot;,&quot;-903.5&quot;:&quot;can-build&quot;,&quot;-902.5&quot;:&quot;can-build&quot;,&quot;-901.5&quot;:&quot;can-build&quot;,&quot;-900.5&quot;:&quot;can-build&quot;},&quot;-6498.5&quot;:{&quot;-914.5&quot;:&quot;can-not-build&quot;,&quot;-913.5&quot;:&quot;reserved-for-pump&quot;,&quot;-912.5&quot;:&quot;reserved-for-pump&quot;,&quot;-911.5&quot;:&quot;reserved-for-pump&quot;,&quot;-910.5&quot;:&quot;reserved-for-pump&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Oilfield4 {
            get {
                return ResourceManager.GetString("Oilfield4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;area&quot;:{&quot;-5463.5&quot;:{&quot;-1094.5&quot;:&quot;can-build&quot;,&quot;-1093.5&quot;:&quot;can-build&quot;,&quot;-1092.5&quot;:&quot;can-build&quot;,&quot;-1091.5&quot;:&quot;can-build&quot;,&quot;-1090.5&quot;:&quot;can-build&quot;,&quot;-1089.5&quot;:&quot;can-build&quot;,&quot;-1088.5&quot;:&quot;can-build&quot;,&quot;-1087.5&quot;:&quot;can-build&quot;,&quot;-1086.5&quot;:&quot;can-build&quot;,&quot;-1085.5&quot;:&quot;can-build&quot;,&quot;-1084.5&quot;:&quot;can-build&quot;,&quot;-1083.5&quot;:&quot;can-build&quot;,&quot;-1082.5&quot;:&quot;can-build&quot;,&quot;-1081.5&quot;:&quot;can-build&quot;,&quot;-1080.5&quot;:&quot;can-build&quot;,&quot;-1079.5&quot;:&quot;can-build&quot;,&quot;-1078.5&quot;:&quot;can-build&quot;},&quot;-5462.5&quot;:{&quot;-1094.5&quot;:&quot;can-build&quot;,&quot;-1093.5&quot;:&quot;can-build&quot;,&quot;-1092.5&quot;:&quot;can-build&quot;,&quot;-1091.5&quot;:&quot;can-build&quot;,&quot;-1090.5&quot;:&quot;can-bui [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Oilfield5 {
            get {
                return ResourceManager.GetString("Oilfield5", resourceCulture);
            }
        }
    }
}
